// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcarr5-67cunRqX25G9sdhGKr_JHzVZYE',
    appId: '1:974863485357:web:b82001a41663b36272f924',
    messagingSenderId: '974863485357',
    projectId: 'caleb-g',
    authDomain: 'caleb-g.firebaseapp.com',
    storageBucket: 'caleb-g.appspot.com',
    measurementId: 'G-NGLMQNCG1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnDzBl1oTjX3MMFSUv4yyx1-K1cRjZMgM',
    appId: '1:974863485357:android:bd7771de05ab439f72f924',
    messagingSenderId: '974863485357',
    projectId: 'caleb-g',
    storageBucket: 'caleb-g.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5jQOfcObYwiAMA82VStwjmupwTJ5vPMQ',
    appId: '1:974863485357:ios:cc9a4af2a2c5e40272f924',
    messagingSenderId: '974863485357',
    projectId: 'caleb-g',
    storageBucket: 'caleb-g.appspot.com',
    iosBundleId: 'com.example.calebg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5jQOfcObYwiAMA82VStwjmupwTJ5vPMQ',
    appId: '1:974863485357:ios:cf6c5fa2b1e9d41072f924',
    messagingSenderId: '974863485357',
    projectId: 'caleb-g',
    storageBucket: 'caleb-g.appspot.com',
    iosBundleId: 'com.example.calebg.RunnerTests',
  );
}
